services:
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=youtube
  app:
    depends_on:
      - db
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=youtube
      - NODE_ENV=production
    volumes:
      - ./videos:/usr/src/app/videos:ro
