services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - dbdata:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - NODE_ENV=production
    volumes:
      - ./videos:/usr/src/app/videos:ro
volumes:
  dbdata:
