name: Check

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
      - name: Build
        run: npm run build
      - name: ESLint
        run: npx eslint .
      - name: Prettier
        run: npx prettier --check .
