name: Check
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm ci
      - name: Build
        run: npm run build
      - name: ESLint
        run: npx --no-install eslint .
      - name: Prettier
        run: npx --no-install prettier --check .
